version : '3'

services:
  backup:
    build: .
    command: /bin/ash -c "./backup.sh /backup /volumes"
    volumes:
      - portainer_portainer_data:/volumes/portainer
      - nginx-proxy_certs:/volumes/nginx-proxy_certs
      - /mnt/Ext_HDD/bakup:/backup

volumes:
  portainer_portainer_data:
    external: true
  nginx-proxy_certs:
    external: true
