version: '3'
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=ItslocalSoIDontCare
      - DB_DATABASE=bookstackapp
      - VIRTUAL_PROTO=https
      - VIRTUAL_HOST=bookstack.manuel.sh
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=bookstack.manuel.sh
    volumes:
      - bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks: 
      - internal
      - autoProxy

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=ItslocalSoIDontCare
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=ItslocalSoIDontCare
    volumes:
      - db:/config
    restart: unless-stopped
    networks: 
      - internal
      
volumes:
  db:
  bookstack:

networks:
  internal:
  autoProxy:
    external: true
