version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - internal

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    environment:
      - POSTGRES_HOST=db
      - VIRTUAL_HOST=data.manuel.sh
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=data.manuel.sh
    ports:
      - 8080:80
    networks:
      - internal
      - autoProxy
    env_file:
      - db.env
    depends_on:
      - db

  cron:
    networks:
      - internal
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db:
  nextcloud:
  data:

networks:
  internal:
  autoProxy:
    external: true
