version: '3'

services:
  dashmachine:
    container_name: dashmachine
    image: manniq31/rmountjoy-dashmachine:arm
    ports:
      - 5002:5000
    volumes:
      - ./config:/DashMachine/config
    environment:
      - VIRTUAL_PORT=5000
      - VIRTUAL_HOST=dash.manuel.sh
      - LETSENCRYPT_HOST=dash.manuel.sh
    networks:
      - autoProxy

networks:
  autoProxy:
    external: true
