version: '3'
services:
  scrutiny:
    image: linuxserver/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
      - VIRTUAL_HOST=portainer.manuel.sh/scrutiny
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.manuel.sh
    volumes:
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/mmcblk0p:/dev/mmcblk0p
    restart: unless-stopped
    networks: 
        - autoProxy

networks:
  autoProxy:
    external: true
