version: '3'
services:
  scrutiny:
    image: linuxserver/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
      - VIRTUAL_HOST=scrutiny.manuel.sh
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=scrutiny.manuel.sh
    volumes:
      - /run/udev:/run/udev:ro
    devices:
      - /dev/sda:/dev/sda
      - /dev/mmcblk0p1:/dev/mmcblk0p1
      - /dev/mmcblk0p2:/dev/mmcblk0p2
    restart: unless-stopped
    networks: 
        - autoProxy

networks:
  autoProxy:
    external: true
