version : '3'

services:
  portainer:
    environment:
      - VIRTUAL_HOST=portainer.manuel.sh
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.manuel.sh
    restart: always
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data
    networks: 
      - autoProxy

volumes:
 portainer_data:

networks:
  autoProxy:
    external: true
