version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    expose:
      - 8086
    networks:
      - grafana
    volumes:
      - influxDb:/vol01/Docker/monitoring
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin 
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    depends_on:
      - influxdb
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    networks:
      - grafana
    

networks:
  grafana:
    external: true

volumes:
  influxDb:
